# Site Settings
baseurl: "/algorithmicsociety"
title: "Société algorithmique"

name: "Société algorithmique"
description: "Une chaire de recherche de l'institut MIAI"
url: "https://github.com/gillesbastin"			

paginate: 3
paginate_path: "blog/page:num"

twitter: "gillesbastin"
email: "gilles.bastin@iepg.fr"

disqus: 
analytics:

copyright: "(ɔ) Chaire Société algorithmique, 2019-2023"	

# Build Settings
permalinks: pretty
